# Generated by Django 4.2.7 on 2023-11-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('sueldoBase', models.CharField(max_length=64)),
                ('telefono', models.CharField(max_length=64)),
                ('dni', models.CharField(max_length=32)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_platosFinalDia', models.CharField(max_length=64)),
                ('cantidad_vasosFinalDia', models.CharField(max_length=64)),
                ('cantidad_cuchillosFinalDia', models.CharField(max_length=64)),
                ('cantidad_tenedoresFinalDia', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDelPlato', models.CharField(max_length=64)),
                ('precioDelPlato', models.CharField(max_length=64)),
                ('descripcionDelPlato', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDeReserva', models.CharField(max_length=64)),
                ('nombre_cliente', models.CharField(max_length=64)),
                ('numero_comensales', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Suministros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreIngrediente', models.CharField(max_length=64)),
                ('nombreBebidas', models.CharField(max_length=64)),
                ('cantidad_Bebidas', models.CharField(max_length=64)),
            ],
        ),
    ]
