# Generated by Django 4.2.7 on 2023-11-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='sueldoBase',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_cuchillosFinalDia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_platosFinalDia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_tenedoresFinalDia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_vasosFinalDia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='precioDelPlato',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='numeroDeReserva',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='numero_comensales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suministros',
            name='cantidad_Bebidas',
            field=models.IntegerField(),
        ),
    ]
