# Generated by Django 4.2.7 on 2023-11-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0002_alter_empleado_sueldobase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministros',
            name='cantidad_ingredienteXbolsa',
            field=models.IntegerField(default=0),
        ),
    ]
